// Katakana and Hiragana characters with their Romaji pairs
export const katakanaRomajiPairs = {
    kata_vowels: {
        a: 'ア',
        i: 'イ',
        u: 'ウ',
        e: 'エ',
        o: 'オ',
    },
    kata_k: {
        ka: 'カ',
        ki: 'キ',
        ku: 'ク',
        ke: 'ケ',
        ko: 'コ',
    },
    kata_s: {
        sa: 'サ',
        shi: 'シ',
        su: 'ス',
        se: 'セ',
        so: 'ソ',
    },
    kata_t: {
        ta: 'タ',
        chi: 'チ',
        tsu: 'ツ',
        te: 'テ',
        to: 'ト',
    },
    kata_n: {
        na: 'ナ',
        ni: 'ニ',
        nu: 'ヌ',
        ne: 'ネ',
        no: 'ノ',
    },
    kata_h: {
        ha: 'ハ',
        hi: 'ヒ',
        fu: 'フ',
        he: 'ヘ',
        ho: 'ホ',
    },
    kata_m: {
        ma: 'マ',
        mi: 'ミ',
        mu: 'ム',
        me: 'メ',
        mo: 'モ',
    },
    kata_y: {
        ya: 'ヤ',
        yu: 'ユ',
        yo: 'ヨ',
    },
    kata_r: {
        ra: 'ラ',
        ri: 'リ',
        ru: 'ル',
        re: 'レ',
        ro: 'ロ',
    },
    kata_w: {
        wa: 'ワ',
        wo: 'ヲ',
    },
    kata_n: {
        n: 'ン',
    },
    kata_g: {
        ga: 'ガ',
        gi: 'ギ',
        gu: 'グ',
        ge: 'ゲ',
        go: 'ゴ',
    },
    kata_z: {
        za: 'ザ',
        ji: 'ジ',
        zu: 'ズ',
        ze: 'ゼ',
        zo: 'ゾ',
    },
    kata_d: {
        da: 'ダ',
        ji: 'ヂ',
        zu: 'ヅ',
        de: 'デ',
        do: 'ド',
    },
    kata_b: {
        ba: 'バ',
        bi: 'ビ',
        bu: 'ブ',
        be: 'ベ',
        bo: 'ボ',
    },
    kata_p: {
        pa: 'パ',
        pi: 'ピ',
        pu: 'プ',
        pe: 'ペ',
        po: 'ポ',
    }
};

export const hiraganaRomajiPairs = {
    hira_vowels: {
        a: 'あ',
        i: 'い',
        u: 'う',
        e: 'え',
        o: 'お',
    },
    hira_k: {
        ka: 'か',
        ki: 'き',
        ku: 'く',
        ke: 'け',
        ko: 'こ',
    },
    hira_s: {
        sa: 'さ',
        shi: 'し',
        su: 'す',
        se: 'せ',
        so: 'そ',
    },
    hira_t: {
        ta: 'た',
        chi: 'ち',
        tsu: 'つ',
        te: 'て',
        to: 'と',
    },
    hira_n: {
        na: 'な',
        ni: 'に',
        nu: 'ぬ',
        ne: 'ね',
        no: 'の',
    },
    hira_h: {
        ha: 'は',
        hi: 'ひ',
        fu: 'ふ',
        he: 'へ',
        ho: 'ほ',
    },
    hira_m: {
        ma: 'ま',
        mi: 'み',
        mu: 'む',
        me: 'め',
        mo: 'も',
    },
    hira_y: {
        ya: 'や',
        yu: 'ゆ',
        yo: 'よ',
    },
    hira_r: {
        ra: 'ら',
        ri: 'り',
        ru: 'る',
        re: 'れ',
        ro: 'ろ',
    },
    hira_w: {
        wa: 'わ',
        wo: 'を',
    },
    hira_n: {
        n: 'ん',
    },
    hira_g: {
        ga: 'が',
        gi: 'ぎ',
        gu: 'ぐ',
        ge: 'げ',
        go: 'ご',
    },
    hira_z: {
        za: 'ざ',
        ji: 'じ',
        zu: 'ず',
        ze: 'ぜ',
        zo: 'ぞ',
    },
    hira_d: {
        da: 'だ',
        ji: 'ぢ',
        zu: 'づ',
        de: 'で',
        do: 'ど',
    },
    hira_b: {
        ba: 'ば',
        bi: 'び',
        bu: 'ぶ',
        be: 'べ',
        bo: 'ぼ',
    },
    hira_p: {
        pa: 'ぱ',
        pi: 'ぴ',
        pu: 'ぷ',
        pe: 'ぺ',
        po: 'ぽ',
    }
};
